--CREATES ROLES 
CREATE ROLE SALESREP;
CREATE ROLE WAREHOUSE;
CREATE ROLE CUSTOMER;

-------------------------------
--MANDAR

--GRANT PERMISSIONS TO ROLE CUSTOMER_ROLE
/
GRANT SELECT ON  INVOICE_VIEW TO CUSTOMER_ROLE;
/

--GRANT PERMISSIONS TO ROLE SALES_REP2
GRANT UPDATE,INSERT,SELECT ON  dev1.CUSTOMER TO SALESREP;
/
GRANT UPDATE,INSERT,SELECT ON  dev1.CUSTOMER_ADDRESS TO SALESREP;
/
GRANT UPDATE,INSERT,SELECT ON  dev1.CUSTOMER_CONTACT TO SALESREP;
/
GRANT UPDATE,INSERT,SELECT ON  dev1.EXTERNAL_TRANSACTION TO SALESREP;
/
GRANT UPDATE,INSERT,SELECT ON  dev1.SALES_REP_ACTIVITY TO SALESREP;
/
GRANT SELECT ON  dev1.PRODUCT TO SALESREP;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.product_price_log TO SALESREP;
--grant permission to views
GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.REP_ACTIVITY_VIEW TO SALESREP;
/
GRANT SELECT ON  dev1.INVENTORY_VIEW TO SALESREP;
/
GRANT SELECT ON  dev1.INVOICE_VIEW TO SALESREP;
/
--grant permission to procedures
grant execute on dev1.insert_ext_tran to salesrep; 
/
grant execute on customer_onboarding to salesrep; 
/
grant execute on dev1.insert_int_tran to salesrep; 
/
grant execute on dev1.insert_sales_rep_activity to salesrep; 
/
--grant permission to functions
grant execute on dev1.update_inventory to salesrep; 
/
grant execute on dev1.invoice_view_rls to salesrep; 
/


--GRANT PERMISSIONS TO ROLE WAREHOUSE_MANAGER_ROLE

GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.CUSTOMER TO WAREHOUSE;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.PRODUCT TO WAREHOUSE;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.CUSTOMER_ADDRESS TO WAREHOUSE;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.CUSTOMER_CONTACT TO WAREHOUSE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.DRIVER_DETAILS TO WAREHOUSE;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.EXTERNAL_TRANSACTION TO WAREHOUSE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.INTERNAL_TRANSACTION TO WAREHOUSE;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON  dev1.INVENTORY TO WAREHOUSE;
/
GRANT SELECT,INSERT,UPDATE ON  dev1.SALES_REP_ACTIVITY TO WAREHOUSE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.SALES_REPRESENTATIVE TO WAREHOUSE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.VEHICLE_DETAILS TO WAREHOUSE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.WAREHOUSE TO WAREHOUSE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON  dev1.product_price_log TO WAREHOUSE;
--grant permission to views
GRANT SELECT ON  dev1.SALES_VIEW TO WAREHOUSE;
/
GRANT SELECT ON  dev1.REP_ACTIVITY_VIEW TO WAREHOUSE;
/
GRANT SELECT ON  dev1.INVENTORY_VIEW TO WAREHOUSE;
/
GRANT SELECT ON  dev1.INVOICE_VIEW TO WAREHOUSE;
/

--grant permission to procedures
grant execute on dev1.insert_int_tran to WAREHOUSE; 
/
grant execute on dev1.update_inventory to WAREHOUSE; 
/
--grant permission to functions
grant execute on dev1.invoice_view_rls to WAREHOUSE; 
/
grant execute on dev1.total_product_sold to WAREHOUSE;
/
----------------------------------------------------
GRANT WAREHOUSE TO WMGR6601;
/
GRANT WAREHOUSE TO WMGR6602;
/
GRANT WAREHOUSE TO WMGR6603;
/
GRANT WAREHOUSE TO WMGR6604;

----------------------------------

GRANT CUSTOMER TO C123008;
/
GRANT CUSTOMER TO C123045;
/
GRANT CUSTOMER TO C123028;
/
GRANT CUSTOMER TO C123011;
------------------------------

GRANT SALESREP TO SREP323001;
/
GRANT SALESREP TO SREP323002;
/
GRANT SALESREP TO SREP323003;
/
GRANT SALESREP TO SREP323004;
/
--------------------------------------
