--CREATE USER WITH PASSWORDS AND ASSIGN USERS TO ROLES
CREATE USER W_MANAGER1 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO W_MANAGER4;
/
GRANT UNLIMITED TABLESPACE  TO W_MANAGER1;
/
GRANT WAREHOUSE_MANAGER_ROLE TO W_MANAGER1;
/
CREATE USER W_MANAGER2 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO W_MANAGER2;
/
GRANT UNLIMITED TABLESPACE  TO W_MANAGER2;
/
GRANT WAREHOUSE_MANAGER_ROLE TO W_MANAGER2;
/
CREATE USER W_MANAGER3 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO W_MANAGER3;
/
GRANT UNLIMITED TABLESPACE  TO W_MANAGER3;
/
GRANT WAREHOUSE_MANAGER_ROLE TO W_MANAGER3;
/
CREATE USER W_MANAGER4 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO W_MANAGER4;
/
GRANT UNLIMITED TABLESPACE  TO W_MANAGER4;
/
GRANT WAREHOUSE_MANAGER_ROLE TO W_MANAGER4;
/
CREATE USER REP1 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO REP1;
/
GRANT UNLIMITED TABLESPACE  TO REP1;
/
GRANT SALES_REP2 TO REP1;
/
CREATE USER REP2 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO REP2;
/
GRANT UNLIMITED TABLESPACE  TO REP2;
/
GRANT REP1 TO REP2;
/
CREATE USER REP3 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO REP3;
/
GRANT UNLIMITED TABLESPACE  TO REP3;
/
GRANT REP2 TO REP3;
/
CREATE USER REP4 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO REP4;
/
GRANT UNLIMITED TABLESPACE  TO REP4;
/
GRANT REP2 TO REP4;
/
CREATE USER CUSTOMER1 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO CUSTOMER1;
/
GRANT UNLIMITED TABLESPACE  TO CUSTOMER1;
/
GRANT CUSTOMER_ROLE TO CUSTOMER1;
/
CREATE USER CUSTOMER2 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO CUSTOMER2;
/
GRANT UNLIMITED TABLESPACE  TO CUSTOMER2;
/
GRANT CUSTOMER_ROLE TO CUSTOMER2;
/
CREATE USER CUSTOMER3 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO CUSTOMER3;
/
GRANT UNLIMITED TABLESPACE  TO CUSTOMER3;
/
GRANT CUSTOMER_ROLE TO CUSTOMER3;
/
CREATE USER CUSTOMER4 IDENTIFIED BY Welcome_123456789;
/
GRANT CREATE SESSION TO CUSTOMER4;
/
GRANT UNLIMITED TABLESPACE  TO CUSTOMER4;
/
GRANT CUSTOMER_ROLE TO CUSTOMER4
/

