SET SERVEROUTPUT ON
/
DECLARE
v_table_exists varchar(1) := 'Y'; 
v_sql varchar(2000);
CURSOR c_fk IS SELECT table_name,constraint_name FROM user_constraints WHERE constraint_type = 'R'; --cursor to store table name and constraint name
CURSOR C_SK IS SELECT SEQUENCE_NAME FROM USER_SEQUENCES;
i Number:=0;                                                                                        --Declare and initalize variable i
V_COUNT NUMBER :=0;
V_COUNT1 NUMBER:=0;--Declare counter 
BEGIN
WHILE i<4                                                                                           --WHILE LOOP TO ITERATE i VARIABLE UNTIL I VALUE IS LESS THAN 3
	LOOP
		i:=i+1;                                                                                     --INCREMENT I VALUE
		SELECT COUNT(*) into V_COUNT FROM user_constraints WHERE constraint_type = 'R' OR constraint_TYPE='U';				--SELECT QUERY TO INSERT NUMBER OF REFRENTIAL KEYS INTO VARIABLE V_COUNT
		SELECT COUNT(*) INTO V_COUNT1 FROM USER_SEQUENCES;	
            if i=1 and V_COUNT>0 THEN                                                               --IF CLAUSE TO CHECK i VALUE AND NUMBER OF VALUES IN V_COUNT VARIABLE
					FOR fk IN c_fk LOOP                                                             --FOR LOOP TO ITERATE CURSOR C_FK
					EXECUTE IMMEDIATE 'ALTER TABLE ' || fk.table_name || ' DROP CONSTRAINT ' || fk.constraint_name; --DROP ALL FOREIGN KEY CONSTRAINTS IN DATABASE
					DBMS_OUTPUT.PUT_LINE('DROPPING FOREIGN KEY CONSTRAINTS FOR TABLE '||fk.table_name);             --DISPLAY DROPPING MESSAGE TO CONSOLE
					END LOOP;
            ELSE IF i=2 and V_COUNT1>0 then
                    for sk in c_sk loop
                    EXECUTE IMMEDIATE 'DROP SEQUENCE '||SK.SEQUENCE_NAME;
                    DBMS_OUTPUT.PUT_LINE('DROPPING SEQUENCES '||SK.SEQUENCE_NAME);
                    END LOOP;
            ELSE IF i=3 THEN                                                                         --CHECK ELSE CONDITION
					for i in(
					SELECT 'CUSTOMER_ADDRESS' TABLE_NAME from dual union all                         --FOR LOOP INITIALIZE TO ITERATE 12 TIMES
					SELECT 'EXTERNAL_TRANSACTION' TABLE_NAME from dual union all
					SELECT 'INTERNAL_TRANSACTION' TABLE_NAME from dual union all
					SELECT 'SALES_REP_ACTIVITY' TABLE_NAME from dual union all
					SELECT 'WAREHOUSE' TABLE_NAME from dual union all
					SELECT 'DRIVER_DETAILS' TABLE_NAME from dual union all
					SELECT 'VEHICLE_DETAILS' TABLE_NAME from dual union all
					SELECT 'PRODUCT' TABLE_NAME from dual union all
					SELECT 'CUSTOMER_CONTACT' TABLE_NAME from dual union all
					SELECT 'CUSTOMER' TABLE_NAME from dual union all
					SELECT 'SALES_REPRESENTATIVE' TABLE_NAME from dual union all
					SELECT 'INVENTORY' TABLE_NAME from dual
					)
					loop
					DBMS_OUTPUT.PUT_LINE('DROPPING TABLE ' || i.TABLE_NAME);									--PRINTING OUTPUT TO CONSOLE WITH DROPPING TABLE NAME															
						BEGIN
							select 'Y' into v_table_exists	from USER_TABLES where TABLE_NAME=i.table_name;		--CHECK IF TABLE EXISTS FROM DATA DICTIONARY VIEW
							v_sql := 'drop table '||i.table_name;                                               
							execute immediate v_sql;
							dbms_output.put_line('Table '||i.table_name||' dropped successfully');              --DROP TABLES PRESENT IN DATABASE
       
							EXCEPTION                                                                           --EXCEPTION HANDLING BLOCK
							when no_data_found then
							dbms_output.put_line('Table already dropped');                                
						END;
					END LOOP;
				dbms_output.put_line('Schema cleanup successfully completed');                                  -- DISPLAYING MESSAGE TO CONSOLE
			END IF;
	END IF; 
    END IF;--END LOOP AND IF STATEMENTS
 END LOOP;
END;
/
CREATE SEQUENCE PRODUCT_SEQ
START WITH 223001
INCREMENT BY 1
NOCYCLE;
/
CREATE TABLE PRODUCT(                                                                                           --DDL STATEMENT TO CREATE TABLE PRODUCT
ID NUMBER,
NAME VARCHAR2(30) NOT NULL,
COST_PRICE NUMBER(20,2) NOT NULL,
SELLING_PRICE NUMBER(20,2) NOT NULL,
PRODUCT_DESCRIPTION VARCHAR2(250) NOT NULL,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(ID)
)
/
insert into product(ID, NAME, COST_PRICE, SELLING_PRICE, PRODUCT_DESCRIPTION)                                      --INSERTING DATA INTO PRODUCT TABLE
values(product_seq.NEXTVAL, 'Tylenol', 8.25,10.5,'It is used to relieve mild headache, toothaches and muscle aches.');
insert into product(ID, NAME, COST_PRICE, SELLING_PRICE, PRODUCT_DESCRIPTION)
values(product_seq.NEXTVAL, 'Pepto bismol', 7.75, 9.75, 'It is used to treat heart burn, nausea and upset stomach.');
insert into product(ID, NAME, COST_PRICE, SELLING_PRICE, PRODUCT_DESCRIPTION)
values(product_seq.NEXTVAL, 'Nyquil syrup',  14, 17.25, 'It is used to relieve coughing,stuffy and runny nose and also for sore throat and sneezing.');
insert into product(ID, NAME, COST_PRICE, SELLING_PRICE, PRODUCT_DESCRIPTION)
values(product_seq.NEXTVAL, 'Imodium',  17.5, 20, 'It is used to treat sudden diarrhea.');
insert into product(ID, NAME, COST_PRICE, SELLING_PRICE, PRODUCT_DESCRIPTION)
values(product_seq.NEXTVAL, 'Mucinex', 22.5,25.5, 'It is used to release chest congestion.');
/
commit;
/
select *from PRODUCT;
/
create sequence customer_seq
start with 123001
increment by 1
nocycle;
/
CREATE TABLE CUSTOMER(                                                                             --DDL STATEMENT TO CREATE CUSTOMER TABLE
ID NUMBER,
CUSTOMER_MEETING_ID NUMBER,
REF_WAREHOUSE_ID NUMBER,
NAME VARCHAR2(50) NOT NULL,
TYPE VARCHAR2(20) NOT NULL,
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(ID)
)
/
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)                           --DML STATEMENTS TO INSERT DATA INTO CUSTOMER TABLE
values (customer_seq.NEXTVAL,	55112201,	6601,	'Nancy Davolio','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112203,	6602,	'Massachusetts General Hospital','Hospital');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112205,	6603,	'CVS Pharmacy','Pharmacy');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112207,	6604,	'Janet Leverling','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112209,	6604,	'Brigham and Womens Hospital','Hospital');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112211,	6602,	'Walgreens','Pharmacy');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112213,	6601,	'Michael Suyama','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112215,	6602,	'Clevland Clinic Hospital','Hospital');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112217,	6603,	'Healthb Mart' ,'Pharmacy');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112219,	6603,	'Robert King','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112221,	6601,	'John Hopkins Hospital','Hospital');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112223,	6602,	'Good Neighbor Pharmacy','Pharmacy');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112225,	6601,	'Anne Dodsworth','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112227,	6604,	'MD Anderson Cancer Center','Hospital');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112229,	6603,	'GNC Live Well','Pharmacy');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112231,	6604,	'Emmy Robinson','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112233,	6601,	'North General Hospital','Hospital');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112235,	6603,	'Safeway Pharmacy','Pharmacy');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112237,	6602,	'Paul Carmody','Doctor');
INSERT INTO CUSTOMER (ID,CUSTOMER_MEETING_ID,REF_WAREHOUSE_ID,NAME,TYPE)
values (customer_seq.NEXTVAL,	55112239,	6603,	'Tucson Medical Center','Hospital');
/
COMMIT;
/
SELECT *FROM CUSTOMER;
/
CREATE TABLE CUSTOMER_ADDRESS(                                                                    --DDL STATEMENT TO CREATE CUSTOMER_ADDRESS TABLE
ID NUMBER,
ADDRESS_LINE_1 VARCHAR2(100),
ADDRESS_LINE_2 VARCHAR2(100),
CITY VARCHAR2(50) NOT NULL,
REGION VARCHAR2(50)NOT NULL,
STATE VARCHAR2(50),
ZIP_CODE NUMBER,
COUNTRY VARCHAR2(50)
)
/
insert into CUSTOMER_ADDRESS (ID, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, REGION, STATE, ZIP_CODE, COUNTRY) --DML STATEMENT TO INSERT TABLE INTO CUSTOMER_ADDRESS TABLE
select 123001, '56C', 'Cape Cod Homes', 'Boston', 'Cambridge', 'MA', 21140, 'USA'  from dual union all
select 123002, '42B', 'Common Wealth', 'Boston', 'Common Wealth', 'MA', 22340, 'USA'  from dual union all
select 123003, '147B', 'Preserve Park Way', 'Boston', 'Roxbury', 'MA', 23634, 'USA'  from dual union all
select 123004, '56C', 'Long Point Road', 'Boston', 'Cambridge', 'MA', 24361, 'USA'  from dual union all
select 123005, '10021', 'Hertiage Port', 'Boston', 'Roxbury', 'MA', 23958, 'USA'  from dual union all
select 123006, '515A', 'Silvia street', 'Boston', 'Common Wealth', 'MA', 21569, 'USA'  from dual union all
select 123007, '500A', '31st Street', 'Boston', 'Cambridge', 'MA', 23569, 'USA'  from dual union all
select 123008, '100W', '38th Street', 'Boston', 'Quincy', 'MA', 22698, 'USA'  from dual union all
select 123009, '555W', 'Lee Road', 'Boston', 'Common Wealth', 'MA', 23200, 'USA'  from dual union all
select 123010, '11535', 'Rockville park', 'Boston', 'Roxbury', 'MA', 21851, 'USA'  from dual union all
select 123011, '18A', 'Hudson Street', 'Boston', 'Cambridge', 'MA', 22978, 'USA'  from dual union all
select 123012, '71C', 'Moody Street', 'Boston', 'Common Wealth', 'MA', 21635, 'USA'  from dual union all
select 123013, '91B', 'Tremont Street', 'Boston', 'Cambridge', 'MA', 24390, 'USA'  from dual union all
select 123014, '107F', 'Summer Street', 'Boston', 'Quincy', 'MA', 23987, 'USA'  from dual union all
select 123015, '56G', '360 Huntington Avenue', 'Boston', 'Roxbury', 'MA', 24548, 'USA'  from dual union all
select 123016, '65L', 'Park Drive', 'Boston', 'Quincy', 'MA', 21578, 'USA'  from dual union all
select 123017, '235S', 'Lower Roxbury', 'Boston', 'Cambridge', 'MA', 23936, 'USA'  from dual union all
select 123018, '125G', 'Parker Hill', 'Boston', 'Roxbury', 'MA', 22546, 'USA'  from dual union all
select 123019, '635C', 'Commonwealth Avenue', 'Boston', 'Common Wealth', 'MA', 23879, 'USA'  from dual union all
select 123020, '32J', 'Washington Street', 'Boston', 'Roxbury', 'MA', 24390, 'USA'  from dual;
/
commit;
/
SELECT *FROM CUSTOMER_ADDRESS;
/
CREATE TABLE CUSTOMER_CONTACT(                                                                 			 --CREATE TABLE CUSTOMER_CONTACT
ID NUMBER,
MOBILE_NO VARCHAR2(30),
EMAIL VARCHAR2(50)
)
/
insert into customer_contact (ID, MOBILE_NO, EMAIL)                                             		 --INSERTING DATA INTO CUSTOMER CONTACT
select 123001, '617-906-1253', 'nancydavolio@gmail.com' from dual union all
select 123002, '857-376-1862', 'salesdept@mgh.org' from dual union all
select 123003, '224-756-7417', 'purchase@cvs.org' from dual union all
select 123004, '224-763-6325', 'janetleverling@gmail.com' from dual union all
select 123005, '732-846-3225', 'salesdept@bwh.org' from dual union all
select 123006, '732-856-3115', 'purchase@walgreens.org'   from dual union all
select 123007, '212-475-5838', 'michaelsuyama@gmail.com'   from dual union all
select 123008, '212-567-6949', 'salesdept@cch.org'   from dual union all
select 123009, '224-875-5415', 'purchase@healthhubmart.org'   from dual union all
select 123010, '857-746-8535', 'robertking@gmail.com'   from dual union all
select 123011, '989-896-5698', 'salesdept@jhh.org'   from dual union all
select 123012, '589-532-8759', 'purchase@.gnp.org'   from dual union all
select 123013, '547-859-7893', 'annedodsworth@gmail.com'   from dual union all
select 123014, '245-589-8965', 'salesdept@macc.org'   from dual union all
select 123015, '896-587-9632', 'purchase@gnclivewall.org'   from dual union all
select 123016, '859-879-6985', 'emmyrobinson@gmail.com'   from dual union all
select 123017, '617-589-9876', 'salesdept@ngh.org'   from dual union all
select 123018, '987-962-5698', 'purchase@safeway.org'   from dual union all
select 123019, '514-859-7892', 'paulcarmody@gmail.com'   from dual union all
select 123020, '879-965-4591', 'salesdept@tmc.org'   from dual;
/
commit;
/
SELECT *FROM CUSTOMER_CONTACT;  
/
create sequence sales_representative_seq
start with 323001
increment by 1
nocycle;                        
/
CREATE TABLE SALES_REPRESENTATIVE(                                                              			--CREATE TABLE SALES_REPRESENTATIVE
ID NUMBER,
REF_WAREHOUSE_ID NUMBER,
FIRST_NAME VARCHAR2(50) NOT NULL,
MIDDLE_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
CONTACT VARCHAR2(30),
EMAIL VARCHAR2(50),
CONSTRAINT SALESREP_ID_PK PRIMARY KEY(ID)
)
/
insert into sales_representative (ID, REF_WAREHOUSE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, CONTACT, EMAIL)  --INSERTING DATA TO  SALES_REPRESENTATIVE TABLE
values (sales_representative_seq.NEXTVAL, 6601, 'John', 'Robert', 'Kenedy', 224-756-1862, 'kennedy.j@organization.com');
insert into sales_representative (ID, REF_WAREHOUSE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, CONTACT, EMAIL)
values (sales_representative_seq.NEXTVAL, 6602, 'Nick', 'Robin', 'Peter', 857-376-1963, 'peter.n@organization.com');
insert into sales_representative (ID, REF_WAREHOUSE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, CONTACT, EMAIL)
values (sales_representative_seq.NEXTVAL, 6603, 'Rock', 'Thomas', 'Edison', 224-876-1932, 'edison.r@organization.com');
insert into sales_representative (ID, REF_WAREHOUSE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, CONTACT, EMAIL)
values (sales_representative_seq.NEXTVAL, 6604, 'Kevin', 'Peter', 'Hart', 857-476-1752, 'hart.k@organization.com');
/
commit;
/
SELECT *FROM SALES_REPRESENTATIVE
/
CREATE SEQUENCE EXTERNAL_TRANSACTION_SEQ
START WITH 23210001
INCREMENT BY 1
NOCYCLE
/ 
CREATE TABLE EXTERNAL_TRANSACTION(																			--CREATING EXTERNAL TRANSACTION TABLE
TRANSACTION_ID NUMBER,
PRODUCT_ID NUMBER,
CUSTOMER_ID NUMBER,
REF_WAREHOUSE_ID NUMBER,
SALESREP_ID NUMBER,
TRANSACTION_TYPE VARCHAR2(20) NOT NULL,
DATE_TIME TIMESTAMP,
QUANTITY NUMBER NOT NULL,
CONSTRAINT TRANSACTION_ID_PK PRIMARY KEY(TRANSACTION_ID)
)
/
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)  --INSERTING DATA INTO EXTERNAL TRANSACTION TABLE
values (external_transaction_seq.NEXTVAL,223001,123004,6604,323004,'P',TO_TIMESTAMP('2023-02-27 11:45:11', 'YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223002,123006,6602,323002,'P',TO_TIMESTAMP('2023-03-02 10:10:02', 'YYYY-MM-DD HH24:MI:SS'),45);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223003,123007,6601,323001,'P',TO_TIMESTAMP('2023-03-07 16:00:39', 'YYYY-MM-DD HH24:MI:SS'),54);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223004,123003,6603,323003,'R',TO_TIMESTAMP('2023-03-16 10:45:44', 'YYYY-MM-DD HH24:MI:SS'),63);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223005,123005,6604,323004,'P',TO_TIMESTAMP('2023-03-17 9:19:44', 'YYYY-MM-DD HH24:MI:SS'),53);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223002,123009,6603,323003,'P',TO_TIMESTAMP('2023-03-17 9:16:44', 'YYYY-MM-DD HH24:MI:SS'),54);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223003,123012,6602,323002,'P',TO_TIMESTAMP('2023-03-17 9:15:44', 'YYYY-MM-DD HH24:MI:SS'),59);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223002,123013,6601,323001,'R',TO_TIMESTAMP('2023-03-17 9:18:44', 'YYYY-MM-DD HH24:MI:SS'),84);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223003,123014,6604,323004,'R',TO_TIMESTAMP('2023-03-17 9:18:44', 'YYYY-MM-DD HH24:MI:SS'),57);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223003,123015,6603,323003,'P',TO_TIMESTAMP('2023-03-18 11:49:44', 'YYYY-MM-DD HH24:MI:SS'),25);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223001,123016,6604,323004,'P',TO_TIMESTAMP('2023-03-18 11:56:44', 'YYYY-MM-DD HH24:MI:SS'),85);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223002,123019,6602,323002,'R',TO_TIMESTAMP('2023-03-18 11:59:44','YYYY-MM-DD HH24:MI:SS'),65);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223001,123020,6603,323003,'R',TO_TIMESTAMP('2023-03-19 12:40:44', 'YYYY-MM-DD HH24:MI:SS'),25);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223003,123010,6603,323003,'P',TO_TIMESTAMP('2023-03-20 11:50:44', 'YYYY-MM-DD HH24:MI:SS'),96);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223001,123011,6601,323001,'P',TO_TIMESTAMP('2023-03-20 11:55:44', 'YYYY-MM-DD HH24:MI:SS'),35);
INSERT INTO EXTERNAL_TRANSACTION(TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,REF_WAREHOUSE_ID,SALESREP_ID,TRANSACTION_TYPE,DATE_TIME,QUANTITY)
values (external_transaction_seq.NEXTVAL,223004,123006,6602,323002,'P',TO_TIMESTAMP('2023-03-20 11:59:44', 'YYYY-MM-DD HH24:MI:SS'),32);
/
commit;
/
SELECT *FROM EXTERNAL_TRANSACTION
/
CREATE SEQUENCE INTERNAL_TRANSACTION_SEQ
START WITH 23210001
INCREMENT BY 1
NOCYCLE
/
CREATE TABLE INTERNAL_TRANSACTION(                                                             --CREATING INTERNAL TRANSACTION TABLE 
TRANSACTION_ID NUMBER,
WAREHOUSE_FROM VARCHAR2(30),
WAREHOUSE_TO VARCHAR2(30),
PRODUCT_ID NUMBER,
SALESREP_ID NUMBER,
DATE_TIME TIMESTAMP,
QUANTITY NUMBER NOT NULL,
CONSTRAINT TRANSACTION_ID1_PK PRIMARY KEY(TRANSACTION_ID)
)
/
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)      --INSERTING DATA INTO INTERNAL TRANSACTION TABLE 
values (internal_transaction_seq.NEXTVAL, 6601, 6602, 223002,  TO_TIMESTAMP('2/27/2023 11:02:11', 'MM-DD-YYYY HH24:MI:SS'),88);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6602, 6604, 223003,  TO_TIMESTAMP('3/2/2023 10:30:02', 'MM-DD-YYYY HH24:MI:SS'),270);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6603, 6602, 223005, TO_TIMESTAMP('3/7/2023 16:09:39', 'MM-DD-YYYY HH24:MI:SS'),100);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6604, 6603, 223004,  TO_TIMESTAMP('3/16/2023 10:40:44', 'MM-DD-YYYY HH24:MI:SS'),140);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 7705, 6601, 223001, TO_TIMESTAMP('3/17/2023 9:15:44', 'MM-DD-YYYY HH24:MI:SS'),1000);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 7705, 6602, 223001,  TO_TIMESTAMP('3/17/2023 9:16:44', 'MM-DD-YYYY HH24:MI:SS'),1000);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 7705, 6603, 223001, TO_TIMESTAMP('3/17/2023 9:17:44', 'MM-DD-YYYY HH24:MI:SS'),1000);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 7705, 6604, 223001, TO_TIMESTAMP('3/17/2023 9:18:44', 'MM-DD-YYYY HH24:MI:SS'),1000);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6601, 6602, 223003,  TO_TIMESTAMP('3/18/2023 10:40:44', 'MM-DD-YYYY HH24:MI:SS'),88);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6602, 6603, 223005,  TO_TIMESTAMP('3/18/2023 11:40:44', 'MM-DD-YYYY HH24:MI:SS'),270);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6603, 6604, 223002,  TO_TIMESTAMP('3/18/2023 11:30:44', 'MM-DD-YYYY HH24:MI:SS'),333);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6604, 6603, 223005,  TO_TIMESTAMP('3/18/2023 11:40:44', 'MM-DD-YYYY HH24:MI:SS'),140);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6603, 6601, 223002,  TO_TIMESTAMP('3/19/2023 11:40:44', 'MM-DD-YYYY HH24:MI:SS'),236);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6602, 6604, 223005,  TO_TIMESTAMP('3/19/2023 11:50:44', 'MM-DD-YYYY HH24:MI:SS'),245);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6601, 6603, 223001,  TO_TIMESTAMP('3/19/2023 11:55:44', 'MM-DD-YYYY HH24:MI:SS'),250);
insert into INTERNAL_TRANSACTION (TRANSACTION_ID, WAREHOUSE_FROM, WAREHOUSE_TO, PRODUCT_ID, DATE_TIME, QUANTITY)
values (internal_transaction_seq.NEXTVAL, 6604, 6601, 223004,  TO_TIMESTAMP('3/19/2023 11:59:44', 'MM-DD-YYYY HH24:MI:SS'),320);/
COMMIT;
/
SELECT *FROM INTERNAL_TRANSACTION;
/ 
CREATE SEQUENCE SALES_REP_ACTIVITY_SEQ
START WITH 55112201
INCREMENT BY 1
NOCYCLE;
/
CREATE TABLE SALES_REP_ACTIVITY(                                                               
MEETING_ID NUMBER,
SALESREP_ID NUMBER,
CUSTOMER_NAME VARCHAR2(50) NOT NULL,
INTERACTION_TYPE VARCHAR2(30),
CUSTOMER_TYPE VARCHAR2(30) CHECK (CUSTOMER_TYPE IN ('in person', 'email', 'on call')),
INTERACTION_DATE TIMESTAMP NOT NULL,
INTERACTION_DURATION NUMBER,
ADDRESS_LINE_1 VARCHAR2(200),
ADDRESS_LINE_2 VARCHAR2(200),
CITY VARCHAR2(50),
REGION VARCHAR2(50),
STATE  VARCHAR2(50),
ZIPCODE NUMBER,
COUNTRY VARCHAR2(30),
MOBILE_NO VARCHAR2(30),
EMAIL_ID VARCHAR2(30),
CUSTOMER_CONVERTED_FLAG VARCHAR2(20) CHECK (CUSTOMER_CONVERTED_FLAG IN ('n', 'y')),
CONSTRAINT MEETING_ID_PK PRIMARY KEY(MEETING_ID)
);
/
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)   --INSERTING DATA INTO SALES_REP_ACTIVITY
values (sales_rep_activity_seq.NEXTVAL, 323001, 'Nancy Davolio', 'IN PERSON','Doctor', TO_TIMESTAMP('2023-01-10 1:02:10', 'YYYY-MM-DD HH24:MI:SS'), 90, '56C', 'Cape Cod Homes', 'Boston', 'Cambridge', 'MA, 21140,'USA',3382896114,'Nancy_Davolio@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323004, 'Mother care', 'EMAIL','Pharmacy', TO_TIMESTAMP('2023-01-11 1:02:10', 'YYYY-MM-DD HH24:MI:SS'), 5, '23D', 'Avenue', 'Boston', 'QUINCY', 'MA', 24661,'USA',0929152613,'Mother_care@gmail.com', 'N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323002, 'Massachusetts General Hospital', 'ON CALL','Hospital', TO_TIMESTAMP('2023-01-13 14:02:15', 'YYYY-MM-DD HH24:MI:SS'), 25, '42B', 'Common wealth', 'Boston', 'Common Wealth', 'MA', 22340,'USA',6718998794,'Massachusetts_General_Hospital@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323002, 'Sarthak Kaur', 'EMAIL','Doctor', TO_TIMESTAMP('2023-01-14 14:02:10', 'YYYY-MM-DD HH24:MI:SS'), 45, '67H', 'Drive', 'Drive', 'Common Wealth', 'MA', 22667,'USA',0734764346,'Sarthak_Kaur@gmail.com', 'N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323003, 'CVS Pharmacy', 'ON CALL','Pharmacy', TO_TIMESTAMP('2023-01-21 15:02:20', 'YYYY-MM-DD HH24:MI:SS'), 40, '147B', 'Preserve Park way', 'Boston', 'Roxbury', 'MA', 23634,'USA',2752580807,'CVS_Pharmacy@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323003, 'Children Hospital', 'ON CALL','Hospital', TO_TIMESTAMP('2023-01-24 15:02:10', 'YYYY-MM-DD HH24:MI:SS'), 55, '55R', 'Cross', 'Boston', 'Roxbury', 'MA', 23997,'USA',6561073629,'Children_Hospital@gmail.com', 'N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323004, 'Janet Leverling', 'EMAIL','Doctor', TO_TIMESTAMP('2023-01-25 18:02:14', 'YYYY-MM-DD HH24:MI:SS'), 5, '100C', 'Long point road', 'Boston', 'Quincy', 'MA', 24361,'USA',2101205999,'Janet_Leverling@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323001, 'Life Care', 'EMAIL','Pharmacy', TO_TIMESTAMP('2023-01-26 18:02:10', 'YYYY-MM-DD HH24:MI:SS'), 5, '778C', 'Longway', 'Boston', 'Cambridge', 'MA', 21339,'USA',4264958592,'Life_Care@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323004, 'Brigham and Womens Hospital', 'IN PERSON','Doctor', TO_TIMESTAMP('2023-02-01 20:02:11', 'YYYY-MM-DD HH24:MI:SS'), 40, '515A', 'Heritage port', 'Boston', 'Quincy', 'MA', 23958,'USA',8149241636,'Brigham_and_Women's_Hospital@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323002, 'Dev Patel', 'ON CALL','Doctor', TO_TIMESTAMP('2023-02-03 9:02:10', 'YYYY-MM-DD HH24:MI:SS'), 50, '88K', 'Fenway', 'Boston', 'Common Wealth', 'MA', 22768,'USA',4221597509,'Dev_Patel@gmail.com', 'N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323002, 'Walgreens', 'IN PERSON','Pharmacy', TO_TIMESTAMP('2023-02-04 9:02:10', 'YYYY-MM-DD HH24:MI:SS'), 25, '500A', 'Silvia street', 'Boston', 'Common Wealth', 'MA', 22598,'USA',0861411695,'Walgreens@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323003, 'Oscar care Hospital', 'ON CALL','Hospital', TO_TIMESTAMP('2023-02-05 10:02:10', 'YYYY-MM-DD HH24:MI:SS'), 5, '589S', 'Subway', 'Boston', 'Roxbury', 'MA', 23998,'USA',8016181022,'Oscar_care_Hospital@gmail.com', 'N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323001, 'Michael Suyama', 'EMAIL','Doctor', TO_TIMESTAMP('2023-02-07 8:12:10', 'YYYY-MM-DD HH24:MI:SS'), 15, '100W', '31st Street', 'Boston', 'Cambridge', 'MA', 21569,'USA',5489540834,'Michael_Suyama@gmail.com', 'Y' );
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323002, 'Access Pharma', 'IN PERSON ','Pharmacy', TO_TIMESTAMP('2023-02-07 10:02:10', 'YYYY-MM-DD HH24:MI:SS'), 35, '234C', 'Highland', 'Boston', 'Common Wealth', 'MA', 22567,'USA',7675577206,'Access_Pharma@gmail.com', 'N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL, 323002, 'Clevland Clinic Hospital', 'ON CALL','Hospital', TO_TIMESTAMP('2023-02-12 10:02:10', 'YYYY-MM-DD HH24:MI:SS'), 45, '555W', '38th Street', 'Boston', 'Roxbury', 'MA', 23569,'USA',9940331012,'Clevland_Clinic_Hospital@gmail.com', 'Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'Rodrigues',  'ON CALL','Doctor',     TO_TIMESTAMP('2023-02-12 10:02:10','YYYY-MM-DD HH24:MI:SS'),45,'64Q','Kirkland','Boston','Quincy','MA',24778,'USA',3748554446,'Rodrigues@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'Healthb Mart', 'EMAIL','Pharmacy',TO_TIMESTAMP('2023-02-13 13:02:10','YYYY-MM-DD HH24:MI:SS'),5,'115A','Lee Road','Boston','Common Wealth','MA',22698,'USA',8238291780,'Healthb_Mart_@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'MediMart','EMAIL','Pharmacy',TO_TIMESTAMP('2023-02-14 13:02:10','YYYY-MM-DD HH24:MI:SS'),5,'225C',     'Street','Boston','Quincy',   'MA',24864,'USA',9145776869,'MediMart@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'Robert King','ON CALL','Doctor',TO_TIMESTAMP('2023-03-07 19:09:18','YYYY-MM-DD HH24:MI:SS'),10,'18A','Rockville park','Boston','Roxbury','MA',23200,'USA',3467522157,'Robert_King@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'Shelly SeniorHospital','EMAIL',      'Hospital',TO_TIMESTAMP('2023-03-08 19:09:18','YYYY-MM-DD HH24:MI:SS'),5,'33A','Range Rock','Boston','Cambridge','MA',  21339,'USA',1315037004,'Shelly_Senior_Hospital@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'John Hopkins Hospital','EMAIL','Hospital',TO_TIMESTAMP('2023-03-08 17:02:10','YYYY-MM-DD HH24:MI:SS'),5 ,'71C','Hudson Street','Boston','Cambridge','MA',21851,'USA',8810924045,'John_Hopkins_Hospital@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323002,'Ravi Sinha','ON CALL','Doctor',TO_TIMESTAMP('2023-03-09 7:02:10','YYYY-MM-DD HH24:MI:SS'),25,'23V','Stepping Stone','Boston','Common Wealth','MA',22556,'USA',6258171031,'Ravi_Sinha@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323002,'Good Neighbor Pharmacy','EMAIL','Pharmacy',TO_TIMESTAMP('2023-03-09 10:08:40','YYYY-MM-DD HH24:MI:SS'),5,'91B','Moody Steet','Boston','Common Wealth','MA',22978,'USA',6358777210,'Good_Neighbor_Pharmacy_@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'City Hospital',    'IN PERSON','Hospital',TO_TIMESTAMP('2023-03-09 15:08:40','YYYY-MM-DD HH24:MI:SS'),45,'78H','Wellington','Boston','Roxbury','MA',23557,'USA',5080126917,'City_Hospital@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'Anne Dodsworth'    ,'ON CALL', 'Doctor',TO_TIMESTAMP('2023-03-09 16:02:10','YYYY-MM-DD HH24:MI:SS'),30,'107F','Tremont Street','Boston','Cambridge','MA',21635,'USA',8794888916,'Anne_Dodsworth@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'Medical', 'EMAIL','Pharmacy',TO_TIMESTAMP('2023-03-09 18:02:10','YYYY-MM-DD HH24:MI:SS'),5,'875F','Washington Avenue','Boston','Quincy','MA',24775,'USA',1465318623,'Medical_@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'MD Anderson Cancer Center', 'EMAIL','Hospital',TO_TIMESTAMP('2023-03-09 20:02:10','YYYY-MM-DD HH24:MI:SS'),5,'56G','Summer Street','Boston','Quincy','MA',24390,'USA',1983459800,'MD_Anderson_Cancer_Center_@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'Wellness Forever', 'ON CALL','Pharmacy',TO_TIMESTAMP('2023-03-09 21:02:10','YYYY-MM-DD HH24:MI:SS'),40,'778C','Driver loop','Boston','Cambridge','MA',21339,'USA',6750509955,'Wellness_Forever@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'GNC Live Well','IN PERSON','Pharmacy',TO_TIMESTAMP('2023-03-10 9:02:10','YYYY-MM-DD HH24:MI:SS'),85,'65L','360 Huntington Avenue','Boston','Roxbury','MA',23987,'USA',7000323188,'GNC_Live_Well@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'Early Responder Hospital','ON CALL','Hospital',TO_TIMESTAMP('2023-03-10 10:02:10','YYYY-MM-DD HH24:MI:SS'),55,'556D','Nusa','Boston','Roxbury','MA',23667,'USA',6437131749,'Early_Responder_Hospital@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'Emmy Robinson','EMAIL','Doctor',TO_TIMESTAMP('2023-03-10 10:02:10','YYYY-MM-DD HH24:MI:SS'),5,'235S','Park Drive','Boston','Quincy','MA',24548,'USA',7936520021,'Emmy_Robinson@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,'Patient Care','IN PERSON' ,'Pharmacy',TO_TIMESTAMP('2023-03-10 14:22:19','YYYY-MM-DD HH24:MI:SS'),75,'1332F','Square street','Boston','Quincy','MA',24335,'USA',7170445870,'Emmy_Robinson@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,'North General Hospital','EMAIL','Hospital',TO_TIMESTAMP('2023-03-10 15:42:50','YYYY-MM-DD HH24:MI:SS'),5,'125G','Lower Roxbury','Boston','Cambridge','MA',21578,'USA',8539735106,'North_General_Hospital@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323002,'Suburban Hospital','IN PERSON','Hospital',TO_TIMESTAMP('2023-03-10 18:42:50','YYYY-MM-DD HH24:MI:SS'),100,'668R','Grip Square','Boston','Common Wealth','MA',22889,'USA',8800933965,'North_General_Hospital@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'Safeway Pharmacy','ON CALL','Pharmacy',TO_TIMESTAMP('2023-03-11 9:47:35','YYYY-MM-DD HH24:MI:SS'),15,'635C','Parker Hill','Boston','Roxbury','MA',23936,'USA',2670619061,'Safeway_Pharmacy@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323002,'Dorthy Pollen','EMAIL','Doctor',TO_TIMESTAMP('2023-03-11 11:47:35','YYYY-MM-DD HH24:MI:SS'),5,'67G','Sanhok','Boston','Common Wealth','MA',22453,'USA',0308516674,'Dorthy_Pollen@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323002,'Paul Carmody','EMAIL','Doctor',TO_TIMESTAMP('2023-03-11 12:24:10','YYYY-MM-DD HH24:MI:SS'),5,'65D','Commonwealth Avenue','Boston','Common Wealth','MA',22546,'USA',3888437157,'Paul_Carmody@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'Highway' ,'ON CALL','Pharmacy',TO_TIMESTAMP('2023-03-11 14:24:10','YYYY-MM-DD HH24:MI:SS'),30,'63E','Closer loop','Boston','Roxbury','MA',23421,'USA',7567785714,'Highway_@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'Tucson Medical Center' ,'IN PERSON','Hospital',TO_TIMESTAMP('2023-03-11 19:05:15','YYYY-MM-DD HH24:MI:SS'),95,'32J','Washington Street','Boston','Roxbury','MA',23879,'USA',1026998482,'Tucson_Medical_Center_@gmail.com','Y');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323003,'Vedicare Hospital','EMAIL','Hospital',TO_TIMESTAMP('2023-03-12 10:05:15','YYYY-MM-DD HH24:MI:SS'),5,'55W','Mission Hill','Boston','Roxbury','MA',23786,'USA',2398690530,'Vedicare_Hospital@gmail.com','N' );
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'Wellington','IN PERSON','Doctor',TO_TIMESTAMP('2023-03-13 10:05:15','YYYY-MM-DD HH24:MI:SS'),70,'78S','Mission Main','Boston','Cambridge','MA',21334,'USA',4191896795,'Wellington@gmail.com','N' );
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323004,'Red Cross' ,'ON CALL','Pharmacy',TO_TIMESTAMP('2023-03-13 15:05:15','YYYY-MM-DD HH24:MI:SS'),25,'60R','Liberty rock','Boston','Quincy','MA',24321,'USA',6599628002,'Red_Cross_@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323002,'Life Saver','EMAIL','Pharmacy',TO_TIMESTAMP('2023-03-13 19:05:15','YYYY-MM-DD HH24:MI:SS'),55,'43T','Pochinki','Boston','Common Wealth','MA',22346,'USA',8549431765,'Life_Saver@gmail.com','N');
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'Kelly Sanders','IN PERSON','Doctor',TO_TIMESTAMP('2023-03-14 10:05:15','YYYY-MM-DD HH24:MI:SS'),75,'65F','Military street','Boston','Cambridge','MA',21346,'USA',7997476947,'Kelly_Sanders@gmail.com','N' );
INSERT INTO SALES_REP_ACTIVITY(MEETING_ID,SALESREP_ID,CUSTOMER_NAME,INTERACTION_TYPE,CUSTOMER_TYPE,INTERACTION_DATE,INTERACTION_DURATION,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,REGION,STATE,ZIPCODE,COUNTRY,MOBILE_NO,EMAIL_ID,CUSTOMER_CONVERTED_FLAG)
values (sales_rep_activity_seq.NEXTVAL,323001,'Bankers Hospital','IN PERSON','Hospital',TO_TIMESTAMP('2023-03-15 10:05:15','YYYY-MM-DD HH24:MI:SS'),65,'435G','Townhall','Boston','Cambridge','MA',21347,'USA',7963135813,'Bankers_Hospital@gmail.com','N'); 
/
commit;
/
SELECT *FROM SALES_REP_ACTIVITY
/
CREATE SEQUENCE INVENTORY_SEQ
START WITH 723001
INCREMENT BY 1
NOCYCLE
/
CREATE TABLE INVENTORY(                                                                           --CREATING TABLE INVENTORY
ID NUMBER,
PRODUCT_ID NUMBER,
WAREHOUSE_ID NUMBER,
PRODUCT_QUANTITY NUMBER NOT NULL,
CONSTRAINT INVENTORY_ID_PK PRIMARY KEY(ID)
)
/
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)                           --INSERTING DATA INTO INVENTORY TABLE
values (inventory_seq.NEXTVAL, 223001, 6601, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223002, 6601, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223003, 6601, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223003, 6603, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223004, 6603, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223005, 6603, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223001, 6604, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223002, 6604, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223003, 6604, 350);
insert into inventory (ID, PRODUCT_ID, WAREHOUSE_ID, PRODUCT_QUANTITY)
values (inventory_seq.NEXTVAL, 223004, 6604, 350);
INSERT INTO INVENTORY(ID,PRODUCT_ID,WAREHOUSE_ID,PRODUCT_QUANTITY)
VALUES(INVENTORY_SEQ.NEXTVAL,223005,6604,350);
/
COMMIT;
/
SELECT *FROM INVENTORY
/
CREATE SEQUENCE WAREHOUSE_SEQ
START WITH 6601
INCREMENT BY 1
NOCYCLE
/
CREATE TABLE WAREHOUSE(                                                                --CREATING WAREHOUSE TABLE
ID NUMBER,
NAME VARCHAR2(50),
ADDRESS VARCHAR2(50),
LOCATION VARCHAR2(50),
REGION VARCHAR2(30),
VEHICLE_ID NUMBER,
CONSTRAINT  WAREHOUSE_ID_PK PRIMARY KEY(ID)
)
/
insert into WAREHOUSE (ID, NAME, ADDRESS, LOCATION, REGION, VEHICLE_ID)                --INSERTING DATA INTO WAREHOUSE TABLE
values (warehouse_seq.NEXTVAL, 'BOS1C','7 Crown Drive, 02169','BOSTON','Cambridge', 823001);
insert into WAREHOUSE (ID, NAME, ADDRESS, LOCATION, REGION, VEHICLE_ID)
values (warehouse_seq.NEXTVAL, 'BOS2W','7583, Common Bridge street, 77054','BOSTON','Commom Wealth', 823002);
insert into WAREHOUSE (ID, NAME, ADDRESS, LOCATION, REGION, VEHICLE_ID)
values (warehouse_seq.NEXTVAL, 'BOS3R','Frank 57 West, 10019', 'BOSTON','Roxbury', 823003);
insert into WAREHOUSE (ID, NAME, ADDRESS, LOCATION, REGION, VEHICLE_ID)
values (warehouse_seq.NEXTVAL, 'BOS4Q','11 Ave Port, 07093','BOSTON','Quincy', 823004);
insert into WAREHOUSE (ID, NAME, ADDRESS, LOCATION, REGION, VEHICLE_ID)
values (warehouse_seq.NEXTVAL, 'CBOSM','235 Park Drive, 02215','BOSTON','Suffolk',823005);
/
COMMIT;
/
SELECT *FROM WAREHOUSE;
/
CREATE SEQUENCE DRIVER_DETAILS_SEQ
START WITH 923001
INCREMENT BY 1
NOCYCLE;
/
CREATE TABLE DRIVER_DETAILS(                                                             --CREATING DRIVER_DETAILS TABLE 
ID NUMBER,
NAME VARCHAR2(50),
CONTACT VARCHAR2(30),
EFFECTIVE_DATE DATE,
LICENCE VARCHAR2(30),
CONSTRAINT DRIVER_ID_PK PRIMARY KEY(ID)
)
/
insert into DRIVER_DETAILS (ID, NAME, CONTACT, EFFECTIVE_DATE, LICENCE)                   --INSERTING DATA INTO DRIVER_DETAILS TABLE
values (driver_details_seq.NEXTVAL, 'John', '212-756-6523', TO_DATE('28/02/2022','DD/MM/YYYY'),'SA9988776');
insert into DRIVER_DETAILS (ID, NAME, CONTACT, EFFECTIVE_DATE, LICENCE)
values (driver_details_seq.NEXTVAL, 'Nick', '616-609-8797', TO_DATE('7/3/2022','DD/MM/YYYY'), 'S99888017');
insert into DRIVER_DETAILS (ID, NAME, CONTACT, EFFECTIVE_DATE, LICENCE)
values (driver_details_seq.NEXTVAL, 'Adam', '716-878-5676', TO_DATE('9/3/2022','DD/MM/YYYY'), 'S15778890');
insert into DRIVER_DETAILS (ID, NAME, CONTACT, EFFECTIVE_DATE, LICENCE)
values (driver_details_seq.NEXTVAL, 'Peter','221-656-6232', TO_DATE('13/3/2022','DD/MM/YYYY'), 'SA8986672');
insert into DRIVER_DETAILS (ID, NAME, CONTACT, EFFECTIVE_DATE, LICENCE)
values (driver_details_seq.NEXTVAL, 'Samuel','331-334-5567', TO_DATE('11/3/2022','DD/MM/YYYY'),'SW668925');
/
commit;
/
SELECT *FROM DRIVER_DETAILS;
/
CREATE SEQUENCE VEHICLE_DETAILS_SEQ
START WITH 823001
INCREMENT BY 1
NOCYCLE
/
CREATE TABLE VEHICLE_DETAILS(                                                               --CREATING VEHICLE_DETAILS TABLE
ID NUMBER,
DRIVER_ID NUMBER,
REGISTRATION_NUMBER VARCHAR2(50),
CONSTRAINT VEHICLE_ID_PK PRIMARY KEY(ID)
)
/
INSERT INTO VEHICLE_DETAILS(ID,DRIVER_ID,REGISTRATION_NUMBER)                               --INSERTING DATA INTO VEHICLE DETAILS TABLE                       
values (vehicle_details_seq.NEXTVAL,923001,'AB-90156');
INSERT INTO VEHICLE_DETAILS(ID,DRIVER_ID,REGISTRATION_NUMBER)
values (vehicle_details_seq.NEXTVAL,923002,'AE-11078');
INSERT INTO VEHICLE_DETAILS(ID,DRIVER_ID,REGISTRATION_NUMBER)
values (vehicle_details_seq.NEXTVAL,923003,'AG-80765');
INSERT INTO VEHICLE_DETAILS(ID,DRIVER_ID,REGISTRATION_NUMBER)
values (vehicle_details_seq.NEXTVAL,923004,'AL-90123');
INSERT INTO VEHICLE_DETAILS(ID,DRIVER_ID,REGISTRATION_NUMBER)
values (vehicle_details_seq.NEXTVAL,923005,'SQ-76431');
/
COMMIT;
/
SELECT *FROM VEHICLE_DETAILS;
/
/
ALTER TABLE CUSTOMER ADD CONSTRAINT "CUSTOMER_MEETING_ID_FK" FOREIGN KEY ("CUSTOMER_MEETING_ID") REFERENCES "SALES_REP_ACTIVITY" ("MEETING_ID")    --CREATING FOREIGN KEY CONSTRAINTS
/
ALTER TABLE CUSTOMER ADD CONSTRAINT "REF_WAREHOUSE_ID_FK" FOREIGN KEY ("REF_WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("ID");
/
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT "CUSTOMER_ID_FK" FOREIGN KEY ("ID") REFERENCES "CUSTOMER" ("ID");
/
ALTER TABLE CUSTOMER_CONTACT ADD CONSTRAINT "CUSTOMER_ID1_FK" FOREIGN KEY ("ID") REFERENCES "CUSTOMER" ("ID")
/
ALTER TABLE SALES_REPRESENTATIVE ADD CONSTRAINT "REF_WAREHOUSE_ID1_FK" FOREIGN KEY ("REF_WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("ID")
/
ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")
/
ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "CUSTOMER_ID2_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("ID")
/
ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "REF_WAREHOUSE_ID2_FK" FOREIGN KEY ("REF_WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("ID")
/
ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "SALESREP_ID_FK" FOREIGN KEY ("SALESREP_ID") REFERENCES "SALES_REPRESENTATIVE" ("ID")
/
ALTER TABLE INTERNAL_TRANSACTION ADD CONSTRAINT "PRODUCT_ID_FK1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")
/
ALTER TABLE INTERNAL_TRANSACTION ADD CONSTRAINT "SALESREP_ID_FK1" FOREIGN KEY ("SALESREP_ID") REFERENCES "SALES_REPRESENTATIVE" ("ID")
/
ALTER TABLE SALES_REP_ACTIVITY ADD CONSTRAINT "SALESREP_ID_FK2" FOREIGN KEY ("SALESREP_ID") REFERENCES "SALES_REPRESENTATIVE" ("ID")
/
ALTER TABLE INVENTORY ADD CONSTRAINT "PRODUCT_ID2_FK" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID")
/
ALTER TABLE INVENTORY ADD CONSTRAINT "WAREHOUSE_ID_FK" FOREIGN KEY ("WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("ID")
/
ALTER TABLE VEHICLE_DETAILS ADD CONSTRAINT "DRIVER_ID_FK" FOREIGN KEY ("DRIVER_ID") REFERENCES "DRIVER_DETAILS" ("ID");
/
alter table driver_details add constraint uni_con unique (contact);
/
ALTER TABLE DRIVER_DETAILS ADD CONSTRAINT UNI_LIC UNIQUE(LICENCE);
/
/