CREATE TABLE PRODUCT(
PRODUCT_ID NUMBER,
PRODUCT_NAME VARCHAR2(30) NOT NULL,
PRODUCT_COST_PRICE NUMBER(20,2) NOT NULL,
PRODUCT_SELLING_PRICE NUMBER(20,2) NOT NULL,
PRODUCT_DESCRIPTION VARCHAR2(50) NOT NULL,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER,
CUSTOMER_MEETING_ID NUMBER,
REF_WAREHOUSE_ID NUMBER,
CUSTOMER_NAME VARCHAR2(50) NOT NULL,
CUSTOMER_TYPE VARCHAR2(20) NOT NULL,
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE CUSTOMER_ADDRESS(
CUSTOMER_ID NUMBER,
ADDRESS_LINE_1 VARCHAR2(100),
ADDRESS_LINE_2 VARCHAR2(100),
CITY VARCHAR2(50) NOT NULL,
REGION VARCHAR2(50)NOT NULL,
STATE VARCHAR2(50),
ZIP_CODE NUMBER,
COUNTRY VARCHAR2(50)
);

CREATE TABLE CUSTOMER_CONTACT(
CUSTOMER_ID NUMBER,
MOBILE_NO VARCHAR2(30),
CUSTOMER_EMAIL VARCHAR2(50)
);

CREATE TABLE SALES_REPRESENTATIVE(
SALESREP_ID NUMBER,
REF_WAREHOUSE_ID NUMBER,
FIRST_NAME VARCHAR2(50) NOT NULL,
MIDDLE_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
SALESREP_CONTACT VARCHAR2(30),
SALESREP_EMAIL VARCHAR2(50)
CONSTRAINT SALESREP_ID_PK PRIMARY KEY(SALESREP_ID)
);

CREATE TABLE EXTERNAL_TRANSACTION(
TRANSACTION_ID NUMBER,
PRODUCT_ID NUMBER,
CUSTOMER_ID NUMBER,
REF_WAREHOUSE_ID NUMBER,
SALESREP_ID NUMBER,
TRANSACTION_TYPE VARCHAR2(20) NOT NULL,
TRANSACTION_DATE_TIME TIMESTAMP,
QUANTITY NUMBER NOT NULL,
CONSTRAINT TRANSACTION_ID_PK PRIMARY KEY(TRANSACTION_ID)
);

CREATE TABLE INTERNAL_TRANSACTION(
TRANSACTION_ID NUMBER,
WAREHOUSE_FROM VARCHAR2(30),
WAREHOUSE_TO VARCHAR2(30),
PRODUCT_ID NUMBER,
SALESREP_ID NUMBER,
TRANSACTION_DATE_TIME TIMESTAMP,
QUANTITY NUMBER NOT NULL,
CONSTRAINT TRANSACTION_ID1_PK PRIMARY KEY(TRANSACTION_ID)
);

CREATE TABLE SALES_REP_ACTIVITY(
MEETING_ID NUMBER,
SALESREP_ID NUMBER,
CUSTOMER_NAME VARCHAR2(50) NOT NULL,
INTERACTION_TYPE VARCHAR2(30),
CUSTOMER_TYPE VARCHAR2(30),
INTERACTION_DATE DATE NOT NULL,
INTERACTION_DURATION VARCHAR2(10),
COMMENTS VARCHAR2(100),
FOLLOWUP_FLAG VARCHAR2(20),
CUSTOMER_CONVERTED_FLAG VARCHAR2(20),
CUSTOMER_CURRENT_ADDRESS VARCHAR2(100) NOT NULL,
CONSTRAINT MEETING_ID_PK PRIMARY KEY(MEETING_ID)
);

CREATE TABLE INVENTORY(
INVENTORY_ID NUMBER,
PRODUCT_ID NUMBER,
WAREHOUSE_ID NUMBER,
PRODUCT_QUANTITY NUMBER NOT NULL,
CONSTRAINT INVENTORY_ID_PK PRIMARY KEY(INVENTORY_ID)
);

CREATE TABLE WAREHOUSE(
WAREHOUSE_ID NUMBER,
WAREHOUSE_NAME VARCHAR2(50),
WAREHOUSE_ADDRESS VARCHAR2(50),
WAREHOUSE_LOCATION VARCHAR2(50),
VEHICLE_ID NUMBER,
CONSTRAINT  WAREHOUSE_ID_PK PRIMARY KEY(WAREHOUSE_ID)
);

CREATE TABLE DRIVER_DETAILS(
DRIVER_ID NUMBER,
DRIVER_NAME VARCHAR2(50),
DRIVER_CONTACT VARCHAR2(30),
EFFECTIVE_DATE DATE,
DRIVER_LICENCE VARCHAR2(30),
CONSTRAINT DRIVER_ID_PK PRIMARY KEY(DRIVER_ID)
);

CREATE TABLE VEHICLE_DETAILS(
VEHICLE_ID NUMBER,
DRIVER_ID NUMBER,
VEHICLE_REGISTRATION_NUMBER VARCHAR2(50),
CONSTRAINT VEHICLE_ID_PK PRIMARY KEY(VEHICLE_ID)
);


ALTER TABLE CUSTOMER ADD CONSTRAINT "CUSTOMER_MEETING_ID_FK" FOREIGN KEY ("CUSTOMER_MEETING_ID") REFERENCES "SALES_REP_ACTIVITY" ("MEETING_ID");

ALTER TABLE CUSTOMER ADD CONSTRAINT "REF_WAREHOUSE_ID_FK" FOREIGN KEY ("REF_WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT "CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("CUSTOMER_ID");

ALTER TABLE CUSTOMER_CONTACT ADD CONSTRAINT "CUSTOMER_ID1_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("CUSTOMER_ID");

ALTER TABLE SALES_REPRESENTATIVE ADD CONSTRAINT "REF_WAREHOUSE_ID1_FK" FOREIGN KEY ("REF_WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "CUSTOMER_ID2_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("CUSTOMER_ID");

ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "REF_WAREHOUSE_ID2_FK" FOREIGN KEY ("REF_WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE EXTERNAL_TRANSACTION ADD CONSTRAINT "SALESREP_ID_FK" FOREIGN KEY ("SALESREP_ID") REFERENCES "SALES_REPRESENTATIVE" ("SALESREP_ID");

ALTER TABLE INTERNAL_TRANSACTION ADD CONSTRAINT "PRODUCT_ID_FK1" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE INTERNAL_TRANSACTION ADD CONSTRAINT "SALESREP_ID_FK1" FOREIGN KEY ("SALESREP_ID") REFERENCES "SALES_REPRESENTATIVE" ("SALESREP_ID");

ALTER TABLE SALES_REP_ACTIVITY ADD CONSTRAINT "SALESREP_ID_FK2" FOREIGN KEY ("SALESREP_ID") REFERENCES "SALES_REPRESENTATIVE" ("SALESREP_ID");

ALTER TABLE INVENTORY ADD CONSTRAINT "PRODUCT_ID2_FK" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("PRODUCT_ID");

ALTER TABLE INVENTORY ADD CONSTRAINT "WAREHOUSE_ID_FK" FOREIGN KEY ("WAREHOUSE_ID") REFERENCES "WAREHOUSE" ("WAREHOUSE_ID");

ALTER TABLE VEHICLE_DETAILS ADD CONSTRAINT "DRIVER_ID_FK" FOREIGN KEY ("DRIVER_ID") REFERENCES "DRIVER_DETAILS" ("DRIVER_ID");
















 