--CREATES ROLES 

--CREATE ROLE MASTER_ADMIN;
/
--CREATE ROLE SALES_REP2;
/
--CREATE ROLE WAREHOUSE_MANAGER_ROLE;
/
--CREATE ROLE CUSTOMER;
/

--GRANT PERMISSIONS TO ROLE MASTER_ADMIN

GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.CUSTOMER TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.CUSTOMER_ADDRESS TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.CUSTOMER_CONTACT TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.DRIVER_DETAILS TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.EXTERNAL_TRANSACTION TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.INTERNAL_TRANSACTION TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.INVENTORY TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.SALES_REP_ACTIVITY TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.SALES_REPRESENTATIVE TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.VEHICLE_DETAILS TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.WAREHOUSE TO MASTER_ADMIN;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.PRODUCT TO MASTER_ADMIN;
/
GRANT SELECT ON DEV1.INVOICE TO CUSTOMER_ROLE;
/
GRANT SELECT ON DEV1.SALES_V TO MASTER_ADMIN;
/
GRANT SELECT ON DEV1.SALES_REP_ACTIVITY_V TO MASTER_ADMIN;
/
GRANT SELECT ON DEV1.INVENTORY_V TO MASTER_ADMIN;

--GRANT PERMISSIONS TO ROLE SALES_REP2
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.CUSTOMER TO SALES_REP2;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.CUSTOMER_ADDRESS TO SALES_REP2;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.CUSTOMER_CONTACT TO SALES_REP2;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.EXTERNAL_TRANSACTION TO SALES_REP2;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.SALES_REP_ACTIVITY TO SALES_REP2;
/
GRANT SELECT ON DEV1.PRODUCT TO SALES_REP2;
/
GRANT SELECT ON DEV1.SALES_REP_ACTIVITY_V TO SALES_R2
/
GRANT SELECT ON DEV1.INVENTORY_V TO SALES_R2
/
GRANT SELECT ON DEV1.INVOICE TO SALES_REP2;

--GRANT PERMISSIONS TO ROLE WAREHOUSE_MANAGER_ROLE

GRANT SELECT ON DEV1.CUSTOMER TO WAREHOUSE_MANAGER_ROLE;

GRANT SELECT ON DEV1.PRODUCT TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.CUSTOMER_ADDRESS TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.CUSTOMER_CONTACT TO WAREHOUSE_MANAGER_ROLE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.DRIVER_DETAILS TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.EXTERNAL_TRANSACTION TO WAREHOUSE_MANAGER_ROLE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.INTERNAL_TRANSACTION TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.INVENTORY TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.SALES_REP_ACTIVITY TO WAREHOUSE_MANAGER_ROLE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.SALES_REPRESENTATIVE TO WAREHOUSE_MANAGER_ROLE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.VEHICLE_DETAILS TO WAREHOUSE_MANAGER_ROLE;
/
GRANT UPDATE,DELETE,INSERT,SELECT ON DEV1.WAREHOUSE TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.SALES_V TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.SALES_REP_ACTIVITY_V TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.INVENTORY_V TO WAREHOUSE_MANAGER_ROLE;
/
GRANT SELECT ON DEV1.INVOICE TO WAREHOUSE_MANAGER_ROLE;
/

--GRANT PERMISSIONS TO ROLE CUSTOMER_ROLE
/
GRANT SELECT ON DEV1.INVOICE TO CUSTOMER_ROLE;
/